name: Upload desktop wallet translations

on:
  workflow_dispatch:
  push:
    paths: ['apps/desktop-wallet/locales/**']
    branches: [next]

jobs:
  upload-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload sources and translations
        uses: crowdin/github-action@v2
        with:
          config: 'apps/desktop-wallet/crowdin.yml'
          upload_sources: true
          upload_translations: true
          download_translations: false
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
